In [1]:
import torch

torch.__version__

'2.4.1+cu118'

In [4]:
# 张量
a = torch.empty(5, 3)
print(a)
print(a.size())
print(a.shape)

tensor([[-1.1290e-36,  1.1869e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
# view
a = torch.randn(4, 4)
print(a)
b = a.view(16)
print(b)
c = a.view(-1, 8)  # -1 的意思是自动计算,第二个维度8个元素,第一个维度自动计算就是2个元素
print(c.shape)

tensor([[ 0.4736,  0.1792, -1.0481, -0.7203],
        [-1.7142, -0.5367, -0.6740, -0.3215],
        [ 1.1932, -0.4617, -0.8050, -1.4000],
        [ 0.0288,  1.4166, -0.5263,  0.9754]])
tensor([ 0.4736,  0.1792, -1.0481, -0.7203, -1.7142, -0.5367, -0.6740, -0.3215,
         1.1932, -0.4617, -0.8050, -1.4000,  0.0288,  1.4166, -0.5263,  0.9754])
tensor([[ 0.4736,  0.1792, -1.0481, -0.7203, -1.7142, -0.5367, -0.6740, -0.3215],
        [ 1.1932, -0.4617, -0.8050, -1.4000,  0.0288,  1.4166, -0.5263,  0.9754]])
torch.Size([2, 8])


In [18]:
a = torch.ones(5)
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [19]:
import numpy as np
a = np.ones((5, 5))
b = torch.from_numpy(a)
print(b)
print(b.shape)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 5])
