In [5]:
import torch

a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
print(b)
print(torch.equal(a, b))
print(torch.eq(a, b))
print(torch.gt(a, b))
print(torch.lt(a, b))

tensor([[0.6122, 0.7863, 0.9516],
        [0.2120, 0.5645, 0.2795]])
tensor([[0.2272, 0.4779, 0.3973],
        [0.2423, 0.0147, 0.5228]])
False
tensor([[False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [ True, False,  True]])


In [15]:
# 排序
a = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]])
torch.sort(a, dim=0, descending=True)

torch.return_types.sort(
values=tensor([[9, 8, 7, 6, 5, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 4, 3, 2, 1, 0]]),
indices=tensor([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]]))

In [22]:
# topk 取最大值
# kthvalue 取最小值
a = torch.rand(3, 4)
print(a)
print(torch.topk(a, k=1, dim=0))
print(torch.kthvalue(a, k=2, dim=0))

tensor([[0.1913, 0.4765, 0.0092, 0.9818],
        [0.1928, 0.3119, 0.2839, 0.3276],
        [0.8315, 0.9723, 0.6694, 0.9426]])
torch.return_types.topk(
values=tensor([[0.8315, 0.9723, 0.6694, 0.9818]]),
indices=tensor([[2, 2, 2, 0]]))
torch.return_types.kthvalue(
values=tensor([0.1928, 0.4765, 0.2839, 0.9426]),
indices=tensor([1, 0, 1, 2]))


In [26]:
a = torch.rand(3, 4)
print(a)
print(torch.isfinite(a))  #判断是否有界
print(torch.isinf(a / 0))
print(torch.isnan(a / 0))  # 判断是否为NAN

tensor([[0.5016, 0.5443, 0.6732, 0.1364],
        [0.4375, 0.4487, 0.5329, 0.2881],
        [0.3376, 0.2370, 0.7427, 0.3528]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
