In [ ]:
# 三角函数
import math
import torch

# 1°=π/180°，1rad=180°/π
# 一周是360度，也是海贪2π弧度，即360°=2π
a = torch.tensor([math.radians(30)])
print(a)
print(torch.cos(a))

In [20]:
import torch

a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float)
print(a)
print(torch.mean(a, dim=0))  # 均值
print(torch.sum(a))  # 总和
print(torch.prod(a))  # 计算所有元素的积
print(torch.argmax(a, dim=0))  # 打印0维,最大值的索引值
print(torch.argmin(a, dim=1))  # 打印1维,最小值的索引值
print("-" * 50)
print(torch.median(a, dim=0))  # 返回中间值
print(torch.mode(a, dim=0))  # 返回众数值

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([4., 5., 6.])
tensor(45.)
tensor(362880.)
tensor([2, 2, 2])
tensor([0, 0, 0])
--------------------------------------------------
torch.return_types.median(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.mode(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))


In [22]:
import torch

torch.manual_seed(1)
mean = torch.rand(1, 2)
print(mean)
std = torch.rand(1, 2)
print(std)
torch.normal(mean, std)

tensor([[0.7576, 0.2793]])
tensor([[0.4031, 0.7347]])


tensor([[0.7825, 0.7358]])