# Tensor常见的形式有哪些
- 0: scalar 数值
- 1: vector 向量
- 2: matrix 矩阵
- 3: n-dimensional tensor 高维

In [9]:
import torch
from torch import tensor
torch.__version__

'2.4.1+cu118'

## Scalar 数值

In [2]:
x = tensor(42.)  # scalar 数值
print(x)
print(f"维度: {x.dim()}")
print(f"x2: {x * 2}")
print(f"item: {x.item()}")

tensor(42.)
维度: 0
x2: 84.0
item: 42.0


## Vector 向量

In [4]:
v = tensor([1, 2, 3])
print(v)
print(f"维度: {v.dim()}")
print(f"size: {v.size()}")

tensor([1, 2, 3])
维度: 1
size: torch.Size([3])


## Matrix 矩阵

In [8]:
m = tensor([[1, 2], [3, 4]])
print(m)
print(f"维度: {m.dim()}")
print(f"size: {m.size()}")
print(m.matmul(m)) # 矩阵相乘
print(tensor([1,0]).matmul(m))
print(tensor([1,2]).matmul(m))

tensor([[1, 2],
        [3, 4]])
维度: 2
size: torch.Size([2, 2])
tensor([[ 7, 10],
        [15, 22]])
tensor([1, 2])
tensor([ 7, 10])


## n-dimensional tensor