In [5]:
import torch

a = torch.tensor([2, 2])
print(a)
print(a.type())
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.type())
c = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.type())

tensor([2, 2])
torch.LongTensor
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.LongTensor
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.FloatTensor


In [7]:
a = torch.rand(2, 2)
print(a)

tensor([[[0.7603, 0.0874],
         [0.3752, 0.0174]],

        [[0.0043, 0.3362],
         [0.7132, 0.4213]]])


In [8]:
a = torch.normal(mean=0.0, std=torch.rand(5))
a

tensor([-0.0726, -0.1407,  0.2383, -0.7009,  0.8585])

In [12]:
a = torch.Tensor(2, 2).uniform_(-1, 1)
a

tensor([[-0.7485,  0.8495],
        [ 0.1740,  0.5815]])

In [16]:
a = torch.arange(0, 10, 3)
a

tensor([0, 3, 6, 9])

In [17]:
# 获取等间隔值
a = torch.linspace(2, 10, 3)
a

tensor([ 2.,  6., 10.])

In [18]:
# 打乱顺序
a = torch.randperm(10)
a

tensor([6, 3, 5, 7, 2, 9, 8, 0, 1, 4])

In [23]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
import torch
a = torch.tensor([3,4],device="cuda")
a

tensor([3, 4], device='cuda:0')