In [39]:
print("pytorch project")

pytorch project


In [40]:

a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [41]:
import torch

b = torch.ones(3)
b

tensor([1., 1., 1.])

In [42]:
c = torch.ones(3, 4)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
b[1]

tensor(1.)

In [44]:
float(b[1])

1.0

In [45]:
b[2] = 100
b

tensor([  1.,   1., 100.])

In [46]:
d = 1
d1 = torch.tensor(d)
d1

tensor(1)

In [47]:
e = [1, 2, 3, 4, 5]
e1 = torch.tensor(e)
e

[1, 2, 3, 4, 5]

In [48]:
import numpy as np

# from_numpy
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr1 = torch.from_numpy(arr)
print(arr1)
arr[0][0] = 100
print(arr)
print(arr1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
tensor([[100,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]], dtype=torch.int32)


In [49]:
f = torch.zeros(3, 3)
f

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [50]:
f[0][0] = 100
f[1][1] = 100
f[2][2] = 100
f

tensor([[100.,   0.,   0.],
        [  0., 100.,   0.],
        [  0.,   0., 100.]])

In [51]:
f1 = torch.zeros_like(f)
f1

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [52]:
aa = torch.ones(5, 5)
aa

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [53]:
bb = torch.full([2, 3], 5)
bb

tensor([[5, 5, 5],
        [5, 5, 5]])

In [54]:
p = torch.full([3, 4], 6)
print(p)
torch.save(p, "../data/p.t")

tensor([[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]])


In [55]:
load_p = torch.load("../data/p.t", weights_only=True)
print(load_p)

tensor([[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]])


In [56]:
# 张量连接
a = torch.ones(4, 5)
print(a)
cat_a = torch.cat([a, a], dim=0)
print(cat_a)
cat_a1 = torch.cat([a, a], dim=1)
cat_a1

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
a = torch.normal(0, 1, [2, 3])
b = torch.normal(0, 1, [2, 3])
print(a)
print(b)
stack_a = torch.stack([a, b], dim=0)
print(stack_a)
stack_b = torch.stack([a, b], dim=1)
print(stack_b)

tensor([[-1.5279,  1.5047, -1.7945],
        [ 0.2703,  0.9163,  0.0464]])
tensor([[ 1.5929, -2.1055,  2.0120],
        [-0.9074, -1.4678, -0.7094]])
tensor([[[-1.5279,  1.5047, -1.7945],
         [ 0.2703,  0.9163,  0.0464]],

        [[ 1.5929, -2.1055,  2.0120],
         [-0.9074, -1.4678, -0.7094]]])
tensor([[[-1.5279,  1.5047, -1.7945],
         [ 1.5929, -2.1055,  2.0120]],

        [[ 0.2703,  0.9163,  0.0464],
         [-0.9074, -1.4678, -0.7094]]])


In [59]:
import sys

print(sys.float_info)

sys.float_info(max=1.7976931348623157e+308, max_exp=1024, max_10_exp=308, min=2.2250738585072014e-308, min_exp=-1021, min_10_exp=-307, dig=15, mant_dig=53, epsilon=2.220446049250313e-16, radix=2, rounds=1)
