In [4]:
import numpy as np

# 向量
vector = np.array([1, 2, 3, 4, 5])
vector_norm = np.linalg.norm(vector)
print(f"Vector:\n{vector}")
print(f"Vector l2 norm:\n{vector_norm}")

Vector:
[1 2 3 4 5]
Vector l2 norm:
7.416198487095663


In [5]:
# 距阵
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_norm = np.linalg.norm(matrix)
print(f"Matrix:\n{matrix}")
print(f"Matrix l2 norm:\n{matrix_norm}")

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix l2 norm:
16.881943016134134


In [6]:
# 张量
tensor = np.array(
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]],
        [[9, 10], [11, 12]],
    ]
)
tensor_norm = np.linalg.norm(tensor)
print(f"Matrix:\n{tensor}")
print(f"Matrix l2 norm:\n{tensor_norm}")

Matrix:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Matrix l2 norm:
25.495097567963924


In [10]:
# 图片
import cv2

# 创建随机二维距阵 黑白
two_d_matrix = np.random.randint(0, 256, (224, 224), dtype=np.uint8)
# 创建随机三维距阵 RGB
three_d_matrix = np.random.randint(0, 256, (3, 224, 224), dtype=np.uint8)

# 交换通道
three_d_matrix_transposed = three_d_matrix.transpose(1, 2, 0)

# cv2.imshow("two_d_matrix", two_d_matrix)
# cv2.imshow("three_d_matrix", three_d_matrix_transposed)
# cv2.waitKey(0)
# 使用OpenCV将图片保存到本地
cv2.imwrite("../images/two_d_matrix.jpg", two_d_matrix)
cv2.imwrite("../images/three_d_matrix.jpg", three_d_matrix_transposed)

True

In [13]:
# 调整图像对比度
image = cv2.imread("../images/o.jpg")
# 增加对比度
increased_contrast = cv2.convertScaleAbs(image, alpha=1.5)
# 较少对比度
decreased_contrast = cv2.convertScaleAbs(image, alpha=0.5)
# 拼接图片
combined_image = cv2.hconcat([image, increased_contrast, decreased_contrast])
cv2.imwrite("../images/combined_image.jpg", combined_image)


True