In [1]:
import torch

a = torch.zeros(2, 4)
b = torch.ones(2, 4)
print(a)
print(b)
print(torch.cat((a, b), dim=0))

KeyboardInterrupt: 

In [10]:
a = torch.linspace(1, 10, 6).view(2, 3)
b = torch.linspace(7, 14, 6).view(2, 3)
print(a)
print(b)
torch.stack((a, b), dim=0)

tensor([[ 1.0000,  2.8000,  4.6000],
        [ 6.4000,  8.2000, 10.0000]])
tensor([[ 7.0000,  8.4000,  9.8000],
        [11.2000, 12.6000, 14.0000]])


tensor([[[ 1.0000,  2.8000,  4.6000],
         [ 6.4000,  8.2000, 10.0000]],

        [[ 7.0000,  8.4000,  9.8000],
         [11.2000, 12.6000, 14.0000]]])