In [2]:
import torch

# torch.chunk

a = torch.rand(3, 4)
print(a)
print(torch.chunk(a, 2, dim=0))


tensor([[0.1710, 0.4024, 0.5296, 0.1457],
        [0.7814, 0.5298, 0.2474, 0.7373],
        [0.9559, 0.0689, 0.7054, 0.1167]])
(tensor([[0.1710, 0.4024, 0.5296, 0.1457],
        [0.7814, 0.5298, 0.2474, 0.7373]]), tensor([[0.9559, 0.0689, 0.7054, 0.1167]]))


In [3]:
import torch

# torch.split
a = torch.rand(3, 4)
print(a)
print(torch.split(a, 2, dim=0))

tensor([[0.9821, 0.3493, 0.6284, 0.6343],
        [0.3831, 0.2414, 0.4707, 0.7215],
        [0.3138, 0.1989, 0.8583, 0.4333]])


(tensor([[0.9821, 0.3493, 0.6284, 0.6343],
         [0.3831, 0.2414, 0.4707, 0.7215]]),
 tensor([[0.3138, 0.1989, 0.8583, 0.4333]]))