In [5]:
import torch

# torch.where
a = torch.rand(4, 4) * 10
b = torch.rand(4, 4) * 10
print(a)
print(b)
out = torch.where(a > 5, a, b)
print("-" * 50)
print(out)

tensor([[9.6149, 6.8737, 2.0303, 8.9637],
        [2.6799, 6.5534, 4.4579, 8.6899],
        [0.5889, 7.6493, 9.9402, 6.9372],
        [1.9605, 1.6705, 2.6085, 3.5094]])
tensor([[3.0680, 4.9434, 6.5742, 1.6552],
        [3.8050, 3.4469, 9.8070, 2.5287],
        [7.4304, 2.7969, 0.0363, 6.9514],
        [4.9474, 8.0637, 5.3759, 3.2700]])
--------------------------------------------------
tensor([[9.6149, 6.8737, 6.5742, 8.9637],
        [3.8050, 6.5534, 9.8070, 8.6899],
        [7.4304, 7.6493, 9.9402, 6.9372],
        [4.9474, 8.0637, 5.3759, 3.2700]])


In [7]:
import torch

# torch.index_select
a = torch.rand(4, 4) * 10
print(a)
print("-" * 50)
out = torch.index_select(a, dim=0, index=torch.tensor([0, 3, 2]))
print(out)

tensor([[6.0149, 5.4959, 4.1879, 3.9598],
        [3.5760, 6.7186, 1.8400, 7.5540],
        [4.6503, 5.0687, 1.9633, 1.9361],
        [5.8355, 1.0371, 2.2583, 4.4848]])
--------------------------------------------------
tensor([[6.0149, 5.4959, 4.1879, 3.9598],
        [5.8355, 1.0371, 2.2583, 4.4848],
        [4.6503, 5.0687, 1.9633, 1.9361]])


In [19]:
import torch

# torch.gather
a = torch.linspace(1, 16, 16).view(4, 4)
# a = torch.rand(4, 4) * 10
print(a)
torch.gather(a, dim=0, index=torch.tensor([
    [0, 1, 1, 1],
    [0, 1, 2, 2]
]))


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])


tensor([[ 1.,  6.,  7.,  8.],
        [ 1.,  6., 11., 12.]])

In [20]:
# torch.masked_select
import torch

a = torch.linspace(1, 16, 16).view(4, 4)
mask = torch.gt(a, 8)
print(a)
print(mask)
print(torch.masked_select(a, mask))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 9., 10., 11., 12., 13., 14., 15., 16.])


In [23]:
import torch

a = torch.linspace(1, 16, 16).view(4, 4)
b = torch.take(a, index=torch.tensor([0, 15, 13, 10]))
print(a)
print(b)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([ 1., 16., 14., 11.])


In [24]:
import torch
a = torch.tensor([[0, 1, 2], [0, 1, 2]])
print(a)
print(torch.nonzero(a))

tensor([[0, 1, 2],
        [0, 1, 2]])
tensor([[0, 1],
        [0, 2],
        [1, 1],
        [1, 2]])
