In [1]:
import torch


In [11]:
# add
a = torch.rand(2, 3)
b = torch.rand(2, 3)
print(a)
a.add_(b)
print(a)

tensor([[0.7824, 0.7560, 0.6236],
        [0.3049, 0.6096, 0.4044]])
tensor([[1.1826, 0.7620, 0.9682],
        [0.4150, 0.9610, 1.3661]])


In [19]:
# 广播
# 1. 进行运算的张量最少有一个维度
# 2. 满足右对齐(相等或者运算的张量有一个为1)
import torch

a = torch.rand(2, 3)
b = torch.rand(3)
print(a)
print(b)
print(a.add_(b))
print(a.shape)

tensor([[0.0834, 0.7662, 0.8638],
        [0.6162, 0.4727, 0.7166]])
tensor([0.1825, 0.2655, 0.3152])
tensor([[0.2659, 1.0317, 1.1790],
        [0.7987, 0.7382, 1.0318]])
torch.Size([2, 3])
