In [ ]:
# 三角函数
import math
import torch

# 1°=π/180°，1rad=180°/π
# 一周是360度，也是海贪2π弧度，即360°=2π
a = torch.tensor([math.radians(30)])
print(a)
print(torch.cos(a))

In [20]:
import torch

a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=torch.float)
print(a)
print(torch.mean(a, dim=0))  # 均值
print(torch.sum(a))  # 总和
print(torch.prod(a))  # 计算所有元素的积
print(torch.argmax(a, dim=0))  # 打印0维,最大值的索引值
print(torch.argmin(a, dim=1))  # 打印1维,最小值的索引值
print("-" * 50)
print(torch.median(a, dim=0))  # 返回中间值
print(torch.mode(a, dim=0))  # 返回众数值

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([4., 5., 6.])
tensor(45.)
tensor(362880.)
tensor([2, 2, 2])
tensor([0, 0, 0])
--------------------------------------------------
torch.return_types.median(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))
torch.return_types.mode(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))


In [22]:
import torch

torch.manual_seed(1)
mean = torch.rand(1, 2)
print(mean)
std = torch.rand(1, 2)
print(std)
torch.normal(mean, std)

tensor([[0.7576, 0.2793]])
tensor([[0.4031, 0.7347]])


tensor([[0.7825, 0.7358]])

In [44]:
import torch


class Line(torch.autograd.Function):
    @staticmethod
    def forward(ctx, w, x, b):
        ctx.save_for_backward(w, x, b)
        return w * x + b

    @staticmethod
    def backward(ctx, *grad_output):
        w, x, b = ctx.saved_tensors
        print(out.type())
        grad_w = grad_output[0] * x
        grad_x = grad_output[0] * w
        grad_b = grad_output[0]
        return grad_w, grad_x, grad_b


w = torch.rand(2, 2, requires_grad=True)
x = torch.rand(2, 2, requires_grad=True)
b = torch.rand(2, 2, requires_grad=True)
print(w)
print(x)
print(b)
print("-" * 50)
out = Line.apply(w, x, b)
print(out)
out.backward(torch.ones_like(out))
print("-" * 50)
print(w.grad)
print(x.grad)
print(b.grad)


tensor([[0.9544, 0.9371],
        [0.2165, 0.9892]], requires_grad=True)
tensor([[0.6237, 0.1679],
        [0.7737, 0.1267]], requires_grad=True)
tensor([[0.9620, 0.1786],
        [0.6414, 0.6523]], requires_grad=True)
--------------------------------------------------
tensor([[1.5572, 0.3359],
        [0.8089, 0.7776]], grad_fn=<LineBackward>)
torch.FloatTensor
tensor([[0.6237, 0.1679],
        [0.7737, 0.1267]])
tensor([[0.9544, 0.9371],
        [0.2165, 0.9892]])
tensor([[1., 1.],
        [1., 1.]])
